#ifndef G_OBJECT_TYPE_H
#define G_OBJECT_TYPE_H

#include "gtypes.h"

enum _GType {
  /* Parquet */
  G_TYPE_SIZE_STATISTICS = 0,
  G_TYPE_STATISTICS,
  G_TYPE_STRING_TYPE,
  G_TYPE_U_U_I_D_TYPE,
  G_TYPE_MAP_TYPE,
  G_TYPE_LIST_TYPE,
  G_TYPE_ENUM_TYPE,
  G_TYPE_DATE_TYPE,
  G_TYPE_FLOAT16_TYPE,
  G_TYPE_NULL_TYPE,
  G_TYPE_DECIMAL_TYPE,
  G_TYPE_MILLI_SECONDS,
  G_TYPE_MICRO_SECONDS,
  G_TYPE_NANO_SECONDS,
  G_TYPE_TIME_UNIT,
  G_TYPE_TIMESTAMP_TYPE,
  G_TYPE_TIME_TYPE,
  G_TYPE_INT_TYPE,
  G_TYPE_JSON_TYPE,
  G_TYPE_BSON_TYPE,
  G_TYPE_VARIANT_TYPE,
  G_TYPE_LOGICAL_TYPE,
  G_TYPE_SCHEMA_ELEMENT,
  G_TYPE_DATA_PAGE_HEADER,
  G_TYPE_INDEX_PAGE_HEADER,
  G_TYPE_DICTIONARY_PAGE_HEADER,
  G_TYPE_DATA_PAGE_HEADER_V2,
  G_TYPE_SPLIT_BLOCK_ALGORITHM,
  G_TYPE_BLOOM_FILTER_ALGORITHM,
  G_TYPE_XX_HASH,
  G_TYPE_BLOOM_FILTER_HASH,
  G_TYPE_UNCOMPRESSED,
  G_TYPE_BLOOM_FILTER_COMPRESSION,
  G_TYPE_BLOOM_FILTER_HEADER,
  G_TYPE_PAGE_HEADER,
  G_TYPE_KEY_VALUE,
  G_TYPE_SORTING_COLUMN,
  G_TYPE_PAGE_ENCODING_STATS,
  G_TYPE_COLUMN_META_DATA,
  G_TYPE_ENCRYPTION_WITH_FOOTER_KEY,
  G_TYPE_ENCRYPTION_WITH_COLUMN_KEY,
  G_TYPE_COLUMN_CRYPTO_META_DATA,
  G_TYPE_COLUMN_CHUNK,
  G_TYPE_ROW_GROUP,
  G_TYPE_TYPE_DEFINED_ORDER,
  G_TYPE_COLUMN_ORDER,
  G_TYPE_PAGE_LOCATION,
  G_TYPE_OFFSET_INDEX,
  G_TYPE_COLUMN_INDEX,
  G_TYPE_AES_GCM_V1,
  G_TYPE_AES_GCM_CTR_V1,
  G_TYPE_ENCRYPTION_ALGORITHM,
  G_TYPE_FILE_META_DATA,
  G_TYPE_FILE_CRYPTO_META_DATA,

  /* Thrift */
  G_TYPE_THRIFT_TRANSPORT,
  G_TYPE_THRIFT_FILE_TRANSPORT,
  G_TYPE_THRIFT_PROTOCOL,
  G_TYPE_THRIFT_COMPACT_PROTOCOL,

  /* Parquet */
  G_TYPE_PARQUET_PLAIN_ENCODER,
  G_TYPE_PARQUET_RLE_BP_ENCODER,
  G_TYPE_COLUMN_READER,
  G_TYPE_COLUMN_WRITER,
  G_TYPE_PARQUET_WRITER,
  G_TYPE_PARQUET_READER,
};
typedef enum _GType GType;

typedef struct _GTypeInstance GTypeInstance;
struct _GTypeInstance {
  GType g_type;
};

static inline gboolean
g_type_check_instance_is_a (GTypeInstance *instance, GType iface_type)
{
  return (instance->g_type == iface_type);
}

#define G_TYPE_CHECK_INSTANCE_CAST(instance, g_type, c_type) \
  ((c_type*) (void *) instance)

#define G_TYPE_CHECK_INSTANCE_TYPE(instance, g_type) \
  (g_type_check_instance_is_a((GTypeInstance*)(instance), g_type))

#define G_TYPE_FROM_INSTANCE(instance) (((GTypeInstance*) (instance))->g_type)

#endif /* G_OBJECT_TYPE_H */
