/*
 * `parquet_types.h` is autogenerated by Thrift Compiler (0.22.0).
 * The only changes in the file is deletion of unused functions.
 */
#ifndef PARQUET_TYPES_H
#define PARQUET_TYPES_H

/* custom thrift includes */
#include "thrift_struct.h"
#include "garray.h"
#include "gobject-type.h"

/* begin types */

enum _Type {
  TYPE_BOOLEAN = 0,
  TYPE_INT32 = 1,
  TYPE_INT64 = 2,
  TYPE_INT96 = 3,
  TYPE_FLOAT = 4,
  TYPE_DOUBLE = 5,
  TYPE_BYTE_ARRAY = 6,
  TYPE_FIXED_LEN_BYTE_ARRAY = 7
};
typedef enum _Type Type;

enum _ConvertedType {
  CONVERTED_TYPE_UTF8 = 0,
  CONVERTED_TYPE_MAP = 1,
  CONVERTED_TYPE_MAP_KEY_VALUE = 2,
  CONVERTED_TYPE_LIST = 3,
  CONVERTED_TYPE_ENUM = 4,
  CONVERTED_TYPE_DECIMAL = 5,
  CONVERTED_TYPE_DATE = 6,
  CONVERTED_TYPE_TIME_MILLIS = 7,
  CONVERTED_TYPE_TIME_MICROS = 8,
  CONVERTED_TYPE_TIMESTAMP_MILLIS = 9,
  CONVERTED_TYPE_TIMESTAMP_MICROS = 10,
  CONVERTED_TYPE_UINT_8 = 11,
  CONVERTED_TYPE_UINT_16 = 12,
  CONVERTED_TYPE_UINT_32 = 13,
  CONVERTED_TYPE_UINT_64 = 14,
  CONVERTED_TYPE_INT_8 = 15,
  CONVERTED_TYPE_INT_16 = 16,
  CONVERTED_TYPE_INT_32 = 17,
  CONVERTED_TYPE_INT_64 = 18,
  CONVERTED_TYPE_JSON = 19,
  CONVERTED_TYPE_BSON = 20,
  CONVERTED_TYPE_INTERVAL = 21
};
typedef enum _ConvertedType ConvertedType;

enum _FieldRepetitionType {
  FIELD_REPETITION_TYPE_REQUIRED = 0,
  FIELD_REPETITION_TYPE_OPTIONAL = 1,
  FIELD_REPETITION_TYPE_REPEATED = 2
};
typedef enum _FieldRepetitionType FieldRepetitionType;

enum _Encoding {
  ENCODING_PLAIN = 0,
  ENCODING_PLAIN_DICTIONARY = 2,
  ENCODING_RLE = 3,
  ENCODING_BIT_PACKED = 4,
  ENCODING_DELTA_BINARY_PACKED = 5,
  ENCODING_DELTA_LENGTH_BYTE_ARRAY = 6,
  ENCODING_DELTA_BYTE_ARRAY = 7,
  ENCODING_RLE_DICTIONARY = 8,
  ENCODING_BYTE_STREAM_SPLIT = 9
};
typedef enum _Encoding Encoding;

enum _CompressionCodec {
  COMPRESSION_CODEC_UNCOMPRESSED = 0,
  COMPRESSION_CODEC_SNAPPY = 1,
  COMPRESSION_CODEC_GZIP = 2,
  COMPRESSION_CODEC_LZO = 3,
  COMPRESSION_CODEC_BROTLI = 4,
  COMPRESSION_CODEC_LZ4 = 5,
  COMPRESSION_CODEC_ZSTD = 6,
  COMPRESSION_CODEC_LZ4_RAW = 7
};
typedef enum _CompressionCodec CompressionCodec;

enum _PageType {
  PAGE_TYPE_DATA_PAGE = 0,
  PAGE_TYPE_INDEX_PAGE = 1,
  PAGE_TYPE_DICTIONARY_PAGE = 2,
  PAGE_TYPE_DATA_PAGE_V2 = 3
};
typedef enum _PageType PageType;

enum _BoundaryOrder {
  BOUNDARY_ORDER_UNORDERED = 0,
  BOUNDARY_ORDER_ASCENDING = 1,
  BOUNDARY_ORDER_DESCENDING = 2
};
typedef enum _BoundaryOrder BoundaryOrder;

/* struct SizeStatistics */
struct _SizeStatistics
{
  ThriftStruct parent;

  /* public */
  gint64 unencoded_byte_array_data_bytes;
  gboolean __isset_unencoded_byte_array_data_bytes;
  GArray * repetition_level_histogram;
  gboolean __isset_repetition_level_histogram;
  GArray * definition_level_histogram;
  gboolean __isset_definition_level_histogram;
};
typedef struct _SizeStatistics SizeStatistics;

GType size_statistics_get_type (void);
gint32
size_statistics_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
gint32
size_statistics_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
void
size_statistics_finalize (GObject *object);
#define TYPE_SIZE_STATISTICS (size_statistics_get_type())
#define SIZE_STATISTICS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SIZE_STATISTICS, SizeStatistics))
void
size_statistics_instance_init (SizeStatistics * object);
#define IS_SIZE_STATISTICS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SIZE_STATISTICS))

/* struct Statistics */
struct _Statistics
{
  ThriftStruct parent;

  /* public */
  GByteArray * max;
  gboolean __isset_max;
  GByteArray * min;
  gboolean __isset_min;
  gint64 null_count;
  gboolean __isset_null_count;
  gint64 distinct_count;
  gboolean __isset_distinct_count;
  GByteArray * max_value;
  gboolean __isset_max_value;
  GByteArray * min_value;
  gboolean __isset_min_value;
  gboolean is_max_value_exact;
  gboolean __isset_is_max_value_exact;
  gboolean is_min_value_exact;
  gboolean __isset_is_min_value_exact;
};
typedef struct _Statistics Statistics;

GType statistics_get_type (void);
gint32
statistics_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
gint32
statistics_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
void
statistics_finalize (GObject *object);
#define TYPE_STATISTICS (statistics_get_type())
#define STATISTICS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_STATISTICS, Statistics))
void
statistics_instance_init (Statistics * object);
#define IS_STATISTICS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_STATISTICS))

/* struct StringType */
struct _StringType
{
  ThriftStruct parent;

  /* public */
};
typedef struct _StringType StringType;

GType string_type_get_type (void);
gint32
string_type_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
gint32
string_type_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
void
string_type_finalize (GObject *object);
#define TYPE_STRING_TYPE (string_type_get_type())
#define STRING_TYPE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_STRING_TYPE, StringType))
void
string_type_instance_init (StringType * object);
#define IS_STRING_TYPE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_STRING_TYPE))

/* struct UUIDType */
struct _UUIDType
{
  ThriftStruct parent;

  /* public */
};
typedef struct _UUIDType UUIDType;

GType u_u_i_d_type_get_type (void);
gint32
u_u_i_d_type_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
gint32
u_u_i_d_type_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
void
u_u_i_d_type_finalize (GObject *object);
#define TYPE_U_U_I_D_TYPE (u_u_i_d_type_get_type())
#define U_U_I_D_TYPE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_U_U_I_D_TYPE, UUIDType))
void
u_u_i_d_type_instance_init (UUIDType * object);
#define IS_U_U_I_D_TYPE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_U_U_I_D_TYPE))

/* struct MapType */
struct _MapType
{
  ThriftStruct parent;

  /* public */
};
typedef struct _MapType MapType;

GType map_type_get_type (void);
gint32
map_type_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
gint32
map_type_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
void
map_type_finalize (GObject *object);
#define TYPE_MAP_TYPE (map_type_get_type())
#define MAP_TYPE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MAP_TYPE, MapType))
void
map_type_instance_init (MapType * object);
#define IS_MAP_TYPE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MAP_TYPE))

/* struct ListType */
struct _ListType
{
  ThriftStruct parent;

  /* public */
};
typedef struct _ListType ListType;

GType list_type_get_type (void);
gint32
list_type_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
gint32
list_type_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
void
list_type_finalize (GObject *object);
#define TYPE_LIST_TYPE (list_type_get_type())
#define LIST_TYPE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_LIST_TYPE, ListType))
void
list_type_instance_init (ListType * object);
#define IS_LIST_TYPE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_LIST_TYPE))

/* struct EnumType */
struct _EnumType
{
  ThriftStruct parent;

  /* public */
};
typedef struct _EnumType EnumType;

GType enum_type_get_type (void);
gint32
enum_type_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
gint32
enum_type_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
void
enum_type_finalize (GObject *object);
#define TYPE_ENUM_TYPE (enum_type_get_type())
#define ENUM_TYPE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_ENUM_TYPE, EnumType))
void
enum_type_instance_init (EnumType * object);
#define IS_ENUM_TYPE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_ENUM_TYPE))

/* struct DateType */
struct _DateType
{
  ThriftStruct parent;

  /* public */
};
typedef struct _DateType DateType;

GType date_type_get_type (void);
gint32
date_type_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
gint32
date_type_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
void
date_type_finalize (GObject *object);
#define TYPE_DATE_TYPE (date_type_get_type())
#define DATE_TYPE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_DATE_TYPE, DateType))
void
date_type_instance_init (DateType * object);
#define IS_DATE_TYPE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_DATE_TYPE))

/* struct Float16Type */
struct _Float16Type
{
  ThriftStruct parent;

  /* public */
};
typedef struct _Float16Type Float16Type;

GType float16_type_get_type (void);
gint32
float16_type_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
gint32
float16_type_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
void
float16_type_finalize (GObject *object);
#define TYPE_FLOAT16_TYPE (float16_type_get_type())
#define FLOAT16_TYPE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_FLOAT16_TYPE, Float16Type))
void
float16_type_instance_init (Float16Type * object);

#define FLOAT16_TYPE_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_FLOAT16_TYPE, Float16TypeClass))
#define IS_FLOAT16_TYPE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_FLOAT16_TYPE))

#define FLOAT16_TYPE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_FLOAT16_TYPE, Float16TypeClass))

/* struct NullType */
struct _NullType
{
  ThriftStruct parent;

  /* public */
};
typedef struct _NullType NullType;

GType null_type_get_type (void);
gint32
null_type_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
gint32
null_type_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
void
null_type_finalize (GObject *object);
#define TYPE_NULL_TYPE (null_type_get_type())
#define NULL_TYPE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_NULL_TYPE, NullType))
void
null_type_instance_init (NullType * object);
#define IS_NULL_TYPE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_NULL_TYPE))

/* struct DecimalType */
struct _DecimalType
{
  ThriftStruct parent;

  /* public */
  gint32 scale;
  gint32 precision;
};
typedef struct _DecimalType DecimalType;

GType decimal_type_get_type (void);
gint32
decimal_type_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
gint32
decimal_type_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
void
decimal_type_finalize (GObject *object);
#define TYPE_DECIMAL_TYPE (decimal_type_get_type())
#define DECIMAL_TYPE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_DECIMAL_TYPE, DecimalType))
void
decimal_type_instance_init (DecimalType * object);
#define IS_DECIMAL_TYPE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_DECIMAL_TYPE))

/* struct MilliSeconds */
struct _MilliSeconds
{
  ThriftStruct parent;

  /* public */
};
typedef struct _MilliSeconds MilliSeconds;

GType milli_seconds_get_type (void);
gint32
milli_seconds_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
gint32
milli_seconds_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
void
milli_seconds_finalize (GObject *object);
#define TYPE_MILLI_SECONDS (milli_seconds_get_type())
#define MILLI_SECONDS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MILLI_SECONDS, MilliSeconds))
void
milli_seconds_instance_init (MilliSeconds * object);
#define IS_MILLI_SECONDS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MILLI_SECONDS))

/* struct MicroSeconds */
struct _MicroSeconds
{
  ThriftStruct parent;

  /* public */
};
typedef struct _MicroSeconds MicroSeconds;

GType micro_seconds_get_type (void);
gint32
micro_seconds_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
gint32
micro_seconds_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
void
micro_seconds_finalize (GObject *object);
#define TYPE_MICRO_SECONDS (micro_seconds_get_type())
#define MICRO_SECONDS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MICRO_SECONDS, MicroSeconds))
void
micro_seconds_instance_init (MicroSeconds * object);
#define IS_MICRO_SECONDS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MICRO_SECONDS))

/* struct NanoSeconds */
struct _NanoSeconds
{
  ThriftStruct parent;

  /* public */
};
typedef struct _NanoSeconds NanoSeconds;

GType nano_seconds_get_type (void);
gint32
nano_seconds_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
gint32
nano_seconds_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
void
nano_seconds_finalize (GObject *object);
#define TYPE_NANO_SECONDS (nano_seconds_get_type())
#define NANO_SECONDS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_NANO_SECONDS, NanoSeconds))
void
nano_seconds_instance_init (NanoSeconds * object);
#define IS_NANO_SECONDS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_NANO_SECONDS))

/* struct TimeUnit */
struct _TimeUnit
{
  ThriftStruct parent;

  /* public */
  MilliSeconds * MILLIS;
  gboolean __isset_MILLIS;
  MicroSeconds * MICROS;
  gboolean __isset_MICROS;
  NanoSeconds * NANOS;
  gboolean __isset_NANOS;
};
typedef struct _TimeUnit TimeUnit;

GType time_unit_get_type (void);
gint32
time_unit_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
gint32
time_unit_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
void
time_unit_finalize (GObject *object);
#define TYPE_TIME_UNIT (time_unit_get_type())
#define TIME_UNIT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TIME_UNIT, TimeUnit))
void
time_unit_instance_init (TimeUnit * object);
#define IS_TIME_UNIT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TIME_UNIT))

/* struct TimestampType */
struct _TimestampType
{
  ThriftStruct parent;

  /* public */
  gboolean isAdjustedToUTC;
  TimeUnit * unit;
};
typedef struct _TimestampType TimestampType;

GType timestamp_type_get_type (void);
gint32
timestamp_type_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
gint32
timestamp_type_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
void
timestamp_type_finalize (GObject *object);
#define TYPE_TIMESTAMP_TYPE (timestamp_type_get_type())
#define TIMESTAMP_TYPE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TIMESTAMP_TYPE, TimestampType))
void
timestamp_type_instance_init (TimestampType * object);
#define IS_TIMESTAMP_TYPE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TIMESTAMP_TYPE))

/* struct TimeType */
struct _TimeType
{
  ThriftStruct parent;

  /* public */
  gboolean isAdjustedToUTC;
  TimeUnit * unit;
};
typedef struct _TimeType TimeType;

GType time_type_get_type (void);
gint32
time_type_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
gint32
time_type_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
void
time_type_finalize (GObject *object);
#define TYPE_TIME_TYPE (time_type_get_type())
#define TIME_TYPE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TIME_TYPE, TimeType))
void
time_type_instance_init (TimeType * object);
#define IS_TIME_TYPE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TIME_TYPE))

/* struct IntType */
struct _IntType
{
  ThriftStruct parent;

  /* public */
  gint8 bitWidth;
  gboolean isSigned;
};
typedef struct _IntType IntType;

GType int_type_get_type (void);
gint32
int_type_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
gint32
int_type_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
void
int_type_finalize (GObject *object);
#define TYPE_INT_TYPE (int_type_get_type())
#define INT_TYPE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_INT_TYPE, IntType))
void
int_type_instance_init (IntType * object);
#define IS_INT_TYPE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_INT_TYPE))

/* struct JsonType */
struct _JsonType
{
  ThriftStruct parent;

  /* public */
};
typedef struct _JsonType JsonType;

GType json_type_get_type (void);
gint32
json_type_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
gint32
json_type_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
void
json_type_finalize (GObject *object);
#define TYPE_JSON_TYPE (json_type_get_type())
#define JSON_TYPE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_JSON_TYPE, JsonType))
void
json_type_instance_init (JsonType * object);
#define IS_JSON_TYPE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_JSON_TYPE))

/* struct BsonType */
struct _BsonType
{
  ThriftStruct parent;

  /* public */
};
typedef struct _BsonType BsonType;

GType bson_type_get_type (void);
gint32
bson_type_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
gint32
bson_type_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
void
bson_type_finalize (GObject *object);
#define TYPE_BSON_TYPE (bson_type_get_type())
#define BSON_TYPE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_BSON_TYPE, BsonType))
void
bson_type_instance_init (BsonType * object);
#define IS_BSON_TYPE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_BSON_TYPE))

/* struct VariantType */
struct _VariantType
{
  ThriftStruct parent;

  /* public */
};
typedef struct _VariantType VariantType;

GType variant_type_get_type (void);
gint32
variant_type_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
gint32
variant_type_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
void
variant_type_finalize (GObject *object);
#define TYPE_VARIANT_TYPE (variant_type_get_type())
#define VARIANT_TYPE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_VARIANT_TYPE, VariantType))
void
variant_type_instance_init (VariantType * object);
#define IS_VARIANT_TYPE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_VARIANT_TYPE))

/* struct LogicalType */
struct _LogicalType
{
  ThriftStruct parent;

  /* public */
  StringType * STRING;
  gboolean __isset_STRING;
  MapType * MAP;
  gboolean __isset_MAP;
  ListType * LIST;
  gboolean __isset_LIST;
  EnumType * ENUM;
  gboolean __isset_ENUM;
  DecimalType * DECIMAL;
  gboolean __isset_DECIMAL;
  DateType * DATE;
  gboolean __isset_DATE;
  TimeType * TIME;
  gboolean __isset_TIME;
  TimestampType * TIMESTAMP;
  gboolean __isset_TIMESTAMP;
  IntType * INTEGER;
  gboolean __isset_INTEGER;
  NullType * UNKNOWN;
  gboolean __isset_UNKNOWN;
  JsonType * JSON;
  gboolean __isset_JSON;
  BsonType * BSON;
  gboolean __isset_BSON;
  UUIDType * UUID;
  gboolean __isset_UUID;
  Float16Type * FLOAT16;
  gboolean __isset_FLOAT16;
  VariantType * VARIANT;
  gboolean __isset_VARIANT;
};
typedef struct _LogicalType LogicalType;

GType logical_type_get_type (void);
gint32
logical_type_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
gint32
logical_type_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
void
logical_type_finalize (GObject *object);
#define TYPE_LOGICAL_TYPE (logical_type_get_type())
#define LOGICAL_TYPE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_LOGICAL_TYPE, LogicalType))
void
logical_type_instance_init (LogicalType * object);
#define IS_LOGICAL_TYPE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_LOGICAL_TYPE))

/* struct SchemaElement */
struct _SchemaElement
{
  ThriftStruct parent;

  /* public */
  Type type;
  gboolean __isset_type;
  gint32 type_length;
  gboolean __isset_type_length;
  FieldRepetitionType repetition_type;
  gboolean __isset_repetition_type;
  gchar * name;
  gint32 num_children;
  gboolean __isset_num_children;
  ConvertedType converted_type;
  gboolean __isset_converted_type;
  gint32 scale;
  gboolean __isset_scale;
  gint32 precision;
  gboolean __isset_precision;
  gint32 field_id;
  gboolean __isset_field_id;
  LogicalType * logicalType;
  gboolean __isset_logicalType;
};
typedef struct _SchemaElement SchemaElement;

GType schema_element_get_type (void);
gint32
schema_element_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
gint32
schema_element_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
void
schema_element_finalize (GObject *object);
#define TYPE_SCHEMA_ELEMENT (schema_element_get_type())
#define SCHEMA_ELEMENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SCHEMA_ELEMENT, SchemaElement))
void
schema_element_instance_init (SchemaElement * object);
#define IS_SCHEMA_ELEMENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SCHEMA_ELEMENT))

/* struct DataPageHeader */
struct _DataPageHeader
{
  ThriftStruct parent;

  /* public */
  gint32 num_values;
  Encoding encoding;
  Encoding definition_level_encoding;
  Encoding repetition_level_encoding;
  Statistics * statistics;
  gboolean __isset_statistics;
};
typedef struct _DataPageHeader DataPageHeader;

GType data_page_header_get_type (void);
gint32
data_page_header_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
gint32
data_page_header_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
void
data_page_header_finalize (GObject *object);
#define TYPE_DATA_PAGE_HEADER (data_page_header_get_type())
#define DATA_PAGE_HEADER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_DATA_PAGE_HEADER, DataPageHeader))
void
data_page_header_instance_init (DataPageHeader * object);
#define IS_DATA_PAGE_HEADER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_DATA_PAGE_HEADER))

/* struct IndexPageHeader */
struct _IndexPageHeader
{
  ThriftStruct parent;

  /* public */
};
typedef struct _IndexPageHeader IndexPageHeader;

GType index_page_header_get_type (void);
gint32
index_page_header_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
gint32
index_page_header_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
void
index_page_header_finalize (GObject *object);
#define TYPE_INDEX_PAGE_HEADER (index_page_header_get_type())
#define INDEX_PAGE_HEADER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_INDEX_PAGE_HEADER, IndexPageHeader))
void
index_page_header_instance_init (IndexPageHeader * object);
#define IS_INDEX_PAGE_HEADER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_INDEX_PAGE_HEADER))

/* struct DictionaryPageHeader */
struct _DictionaryPageHeader
{
  ThriftStruct parent;

  /* public */
  gint32 num_values;
  Encoding encoding;
  gboolean is_sorted;
  gboolean __isset_is_sorted;
};
typedef struct _DictionaryPageHeader DictionaryPageHeader;

GType dictionary_page_header_get_type (void);
gint32
dictionary_page_header_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
gint32
dictionary_page_header_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
void
dictionary_page_header_finalize (GObject *object);
#define TYPE_DICTIONARY_PAGE_HEADER (dictionary_page_header_get_type())
#define DICTIONARY_PAGE_HEADER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_DICTIONARY_PAGE_HEADER, DictionaryPageHeader))
void
dictionary_page_header_instance_init (DictionaryPageHeader * object);
#define IS_DICTIONARY_PAGE_HEADER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_DICTIONARY_PAGE_HEADER))

/* struct DataPageHeaderV2 */
struct _DataPageHeaderV2
{
  ThriftStruct parent;

  /* public */
  gint32 num_values;
  gint32 num_nulls;
  gint32 num_rows;
  Encoding encoding;
  gint32 definition_levels_byte_length;
  gint32 repetition_levels_byte_length;
  gboolean is_compressed;
  gboolean __isset_is_compressed;
  Statistics * statistics;
  gboolean __isset_statistics;
};
typedef struct _DataPageHeaderV2 DataPageHeaderV2;

GType data_page_header_v2_get_type (void);
gint32
data_page_header_v2_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
gint32
data_page_header_v2_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
void
data_page_header_v2_finalize (GObject *object);
#define TYPE_DATA_PAGE_HEADER_V2 (data_page_header_v2_get_type())
#define DATA_PAGE_HEADER_V2(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_DATA_PAGE_HEADER_V2, DataPageHeaderV2))
void
data_page_header_v2_instance_init (DataPageHeaderV2 * object);

#define DATA_PAGE_HEADER_V2_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_DATA_PAGE_HEADER_V2, DataPageHeaderV2Class))
#define IS_DATA_PAGE_HEADER_V2(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_DATA_PAGE_HEADER_V2))

#define DATA_PAGE_HEADER_V2_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_DATA_PAGE_HEADER_V2, DataPageHeaderV2Class))

/* struct SplitBlockAlgorithm */
struct _SplitBlockAlgorithm
{
  ThriftStruct parent;

  /* public */
};
typedef struct _SplitBlockAlgorithm SplitBlockAlgorithm;

GType split_block_algorithm_get_type (void);
gint32
split_block_algorithm_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
gint32
split_block_algorithm_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
void
split_block_algorithm_finalize (GObject *object);
#define TYPE_SPLIT_BLOCK_ALGORITHM (split_block_algorithm_get_type())
#define SPLIT_BLOCK_ALGORITHM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SPLIT_BLOCK_ALGORITHM, SplitBlockAlgorithm))
void
split_block_algorithm_instance_init (SplitBlockAlgorithm * object);
#define IS_SPLIT_BLOCK_ALGORITHM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SPLIT_BLOCK_ALGORITHM))

/* struct BloomFilterAlgorithm */
struct _BloomFilterAlgorithm
{
  ThriftStruct parent;

  /* public */
  SplitBlockAlgorithm * BLOCK;
  gboolean __isset_BLOCK;
};
typedef struct _BloomFilterAlgorithm BloomFilterAlgorithm;

GType bloom_filter_algorithm_get_type (void);
gint32
bloom_filter_algorithm_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
gint32
bloom_filter_algorithm_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
void
bloom_filter_algorithm_finalize (GObject *object);
#define TYPE_BLOOM_FILTER_ALGORITHM (bloom_filter_algorithm_get_type())
#define BLOOM_FILTER_ALGORITHM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_BLOOM_FILTER_ALGORITHM, BloomFilterAlgorithm))
void
bloom_filter_algorithm_instance_init (BloomFilterAlgorithm * object);
#define IS_BLOOM_FILTER_ALGORITHM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_BLOOM_FILTER_ALGORITHM))

/* struct XxHash */
struct _XxHash
{
  ThriftStruct parent;

  /* public */
};
typedef struct _XxHash XxHash;

GType xx_hash_get_type (void);
gint32
xx_hash_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
gint32
xx_hash_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
void
xx_hash_finalize (GObject *object);
#define TYPE_XX_HASH (xx_hash_get_type())
#define XX_HASH(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_XX_HASH, XxHash))
void
xx_hash_instance_init (XxHash * object);
#define IS_XX_HASH(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_XX_HASH))

/* struct BloomFilterHash */
struct _BloomFilterHash
{
  ThriftStruct parent;

  /* public */
  XxHash * XXHASH;
  gboolean __isset_XXHASH;
};
typedef struct _BloomFilterHash BloomFilterHash;

GType bloom_filter_hash_get_type (void);
gint32
bloom_filter_hash_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
gint32
bloom_filter_hash_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
void
bloom_filter_hash_finalize (GObject *object);
#define TYPE_BLOOM_FILTER_HASH (bloom_filter_hash_get_type())
#define BLOOM_FILTER_HASH(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_BLOOM_FILTER_HASH, BloomFilterHash))
void
bloom_filter_hash_instance_init (BloomFilterHash * object);
#define IS_BLOOM_FILTER_HASH(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_BLOOM_FILTER_HASH))

/* struct Uncompressed */
struct _Uncompressed
{
  ThriftStruct parent;

  /* public */
};
typedef struct _Uncompressed Uncompressed;

GType uncompressed_get_type (void);
gint32
uncompressed_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
gint32
uncompressed_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
void
uncompressed_finalize (GObject *object);
#define TYPE_UNCOMPRESSED (uncompressed_get_type())
#define UNCOMPRESSED(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_UNCOMPRESSED, Uncompressed))
void
uncompressed_instance_init (Uncompressed * object);
#define IS_UNCOMPRESSED(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_UNCOMPRESSED))

/* struct BloomFilterCompression */
struct _BloomFilterCompression
{
  ThriftStruct parent;

  /* public */
  Uncompressed * UNCOMPRESSED;
  gboolean __isset_UNCOMPRESSED;
};
typedef struct _BloomFilterCompression BloomFilterCompression;

GType bloom_filter_compression_get_type (void);
gint32
bloom_filter_compression_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
gint32
bloom_filter_compression_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
void
bloom_filter_compression_finalize (GObject *object);
#define TYPE_BLOOM_FILTER_COMPRESSION (bloom_filter_compression_get_type())
#define BLOOM_FILTER_COMPRESSION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_BLOOM_FILTER_COMPRESSION, BloomFilterCompression))
void
bloom_filter_compression_instance_init (BloomFilterCompression * object);
#define IS_BLOOM_FILTER_COMPRESSION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_BLOOM_FILTER_COMPRESSION))

/* struct BloomFilterHeader */
struct _BloomFilterHeader
{
  ThriftStruct parent;

  /* public */
  gint32 numBytes;
  BloomFilterAlgorithm * algorithm;
  BloomFilterHash * hash;
  BloomFilterCompression * compression;
};
typedef struct _BloomFilterHeader BloomFilterHeader;

GType bloom_filter_header_get_type (void);
gint32
bloom_filter_header_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
gint32
bloom_filter_header_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
void
bloom_filter_header_finalize (GObject *object);
#define TYPE_BLOOM_FILTER_HEADER (bloom_filter_header_get_type())
#define BLOOM_FILTER_HEADER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_BLOOM_FILTER_HEADER, BloomFilterHeader))
void
bloom_filter_header_instance_init (BloomFilterHeader * object);
#define IS_BLOOM_FILTER_HEADER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_BLOOM_FILTER_HEADER))

/* struct PageHeader */
struct _PageHeader
{
  ThriftStruct parent;

  /* public */
  PageType type;
  gint32 uncompressed_page_size;
  gint32 compressed_page_size;
  gint32 crc;
  gboolean __isset_crc;
  DataPageHeader * data_page_header;
  gboolean __isset_data_page_header;
  IndexPageHeader * index_page_header;
  gboolean __isset_index_page_header;
  DictionaryPageHeader * dictionary_page_header;
  gboolean __isset_dictionary_page_header;
  DataPageHeaderV2 * data_page_header_v2;
  gboolean __isset_data_page_header_v2;
};
typedef struct _PageHeader PageHeader;

GType page_header_get_type (void);
gint32
page_header_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
gint32
page_header_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
void
page_header_finalize (GObject *object);
#define TYPE_PAGE_HEADER (page_header_get_type())
#define PAGE_HEADER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_PAGE_HEADER, PageHeader))
void
page_header_instance_init (PageHeader * object);
#define IS_PAGE_HEADER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_PAGE_HEADER))

/* struct KeyValue */
struct _KeyValue
{
  ThriftStruct parent;

  /* public */
  gchar * key;
  gchar * value;
  gboolean __isset_value;
};
typedef struct _KeyValue KeyValue;

GType key_value_get_type (void);
gint32
key_value_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
gint32
key_value_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
void
key_value_finalize (GObject *object);
#define TYPE_KEY_VALUE (key_value_get_type())
#define KEY_VALUE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_KEY_VALUE, KeyValue))
void
key_value_instance_init (KeyValue * object);
#define IS_KEY_VALUE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_KEY_VALUE))

/* struct SortingColumn */
struct _SortingColumn
{
  ThriftStruct parent;

  /* public */
  gint32 column_idx;
  gboolean descending;
  gboolean nulls_first;
};
typedef struct _SortingColumn SortingColumn;

GType sorting_column_get_type (void);
gint32
sorting_column_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
gint32
sorting_column_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
void
sorting_column_finalize (GObject *object);
#define TYPE_SORTING_COLUMN (sorting_column_get_type())
#define SORTING_COLUMN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SORTING_COLUMN, SortingColumn))
void
sorting_column_instance_init (SortingColumn * object);
#define IS_SORTING_COLUMN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SORTING_COLUMN))

/* struct PageEncodingStats */
struct _PageEncodingStats
{
  ThriftStruct parent;

  /* public */
  PageType page_type;
  Encoding encoding;
  gint32 count;
};
typedef struct _PageEncodingStats PageEncodingStats;

GType page_encoding_stats_get_type (void);
gint32
page_encoding_stats_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
gint32
page_encoding_stats_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
void
page_encoding_stats_finalize (GObject *object);
#define TYPE_PAGE_ENCODING_STATS (page_encoding_stats_get_type())
#define PAGE_ENCODING_STATS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_PAGE_ENCODING_STATS, PageEncodingStats))
void
page_encoding_stats_instance_init (PageEncodingStats * object);
#define IS_PAGE_ENCODING_STATS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_PAGE_ENCODING_STATS))

/* struct ColumnMetaData */
struct _ColumnMetaData
{
  ThriftStruct parent;

  /* public */
  Type type;
  GArray * encodings;
  GPtrArray * path_in_schema;
  CompressionCodec codec;
  gint64 num_values;
  gint64 total_uncompressed_size;
  gint64 total_compressed_size;
  GPtrArray * key_value_metadata;
  gboolean __isset_key_value_metadata;
  gint64 data_page_offset;
  gint64 index_page_offset;
  gboolean __isset_index_page_offset;
  gint64 dictionary_page_offset;
  gboolean __isset_dictionary_page_offset;
  Statistics * statistics;
  gboolean __isset_statistics;
  GPtrArray * encoding_stats;
  gboolean __isset_encoding_stats;
  gint64 bloom_filter_offset;
  gboolean __isset_bloom_filter_offset;
  gint32 bloom_filter_length;
  gboolean __isset_bloom_filter_length;
  SizeStatistics * size_statistics;
  gboolean __isset_size_statistics;
};
typedef struct _ColumnMetaData ColumnMetaData;

GType column_meta_data_get_type (void);
gint32
column_meta_data_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
gint32
column_meta_data_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
void
column_meta_data_finalize (GObject *object);
#define TYPE_COLUMN_META_DATA (column_meta_data_get_type())
#define COLUMN_META_DATA(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_COLUMN_META_DATA, ColumnMetaData))
void
column_meta_data_instance_init (ColumnMetaData * object);
#define IS_COLUMN_META_DATA(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_COLUMN_META_DATA))

/* struct EncryptionWithFooterKey */
struct _EncryptionWithFooterKey
{
  ThriftStruct parent;

  /* public */
};
typedef struct _EncryptionWithFooterKey EncryptionWithFooterKey;

GType encryption_with_footer_key_get_type (void);
gint32
encryption_with_footer_key_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
gint32
encryption_with_footer_key_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
void
encryption_with_footer_key_finalize (GObject *object);
#define TYPE_ENCRYPTION_WITH_FOOTER_KEY (encryption_with_footer_key_get_type())
#define ENCRYPTION_WITH_FOOTER_KEY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_ENCRYPTION_WITH_FOOTER_KEY, EncryptionWithFooterKey))
void
encryption_with_footer_key_instance_init (EncryptionWithFooterKey * object);
#define IS_ENCRYPTION_WITH_FOOTER_KEY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_ENCRYPTION_WITH_FOOTER_KEY))

/* struct EncryptionWithColumnKey */
struct _EncryptionWithColumnKey
{
  ThriftStruct parent;

  /* public */
  GPtrArray * path_in_schema;
  GByteArray * key_metadata;
  gboolean __isset_key_metadata;
};
typedef struct _EncryptionWithColumnKey EncryptionWithColumnKey;

GType encryption_with_column_key_get_type (void);
gint32
encryption_with_column_key_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
gint32
encryption_with_column_key_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
void
encryption_with_column_key_finalize (GObject *object);
#define TYPE_ENCRYPTION_WITH_COLUMN_KEY (encryption_with_column_key_get_type())
#define ENCRYPTION_WITH_COLUMN_KEY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_ENCRYPTION_WITH_COLUMN_KEY, EncryptionWithColumnKey))
void
encryption_with_column_key_instance_init (EncryptionWithColumnKey * object);
#define IS_ENCRYPTION_WITH_COLUMN_KEY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_ENCRYPTION_WITH_COLUMN_KEY))

/* struct ColumnCryptoMetaData */
struct _ColumnCryptoMetaData
{
  ThriftStruct parent;

  /* public */
  EncryptionWithFooterKey * ENCRYPTION_WITH_FOOTER_KEY;
  gboolean __isset_ENCRYPTION_WITH_FOOTER_KEY;
  EncryptionWithColumnKey * ENCRYPTION_WITH_COLUMN_KEY;
  gboolean __isset_ENCRYPTION_WITH_COLUMN_KEY;
};
typedef struct _ColumnCryptoMetaData ColumnCryptoMetaData;

GType column_crypto_meta_data_get_type (void);
gint32
column_crypto_meta_data_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
gint32
column_crypto_meta_data_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
void
column_crypto_meta_data_finalize (GObject *object);
#define TYPE_COLUMN_CRYPTO_META_DATA (column_crypto_meta_data_get_type())
#define COLUMN_CRYPTO_META_DATA(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_COLUMN_CRYPTO_META_DATA, ColumnCryptoMetaData))
void
column_crypto_meta_data_instance_init (ColumnCryptoMetaData * object);
#define IS_COLUMN_CRYPTO_META_DATA(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_COLUMN_CRYPTO_META_DATA))

/* struct ColumnChunk */
struct _ColumnChunk
{
  ThriftStruct parent;

  /* public */
  gchar * file_path;
  gboolean __isset_file_path;
  gint64 file_offset;
  ColumnMetaData * meta_data;
  gboolean __isset_meta_data;
  gint64 offset_index_offset;
  gboolean __isset_offset_index_offset;
  gint32 offset_index_length;
  gboolean __isset_offset_index_length;
  gint64 column_index_offset;
  gboolean __isset_column_index_offset;
  gint32 column_index_length;
  gboolean __isset_column_index_length;
  ColumnCryptoMetaData * crypto_metadata;
  gboolean __isset_crypto_metadata;
  GByteArray * encrypted_column_metadata;
  gboolean __isset_encrypted_column_metadata;
};
typedef struct _ColumnChunk ColumnChunk;

GType column_chunk_get_type (void);
gint32
column_chunk_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
gint32
column_chunk_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
void
column_chunk_finalize (GObject *object);
#define TYPE_COLUMN_CHUNK (column_chunk_get_type())
#define COLUMN_CHUNK(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_COLUMN_CHUNK, ColumnChunk))
void
column_chunk_instance_init (ColumnChunk * object);
#define IS_COLUMN_CHUNK(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_COLUMN_CHUNK))

/* struct RowGroup */
struct _RowGroup
{
  ThriftStruct parent;

  /* public */
  GPtrArray * columns;
  gint64 total_byte_size;
  gint64 num_rows;
  GPtrArray * sorting_columns;
  gboolean __isset_sorting_columns;
  gint64 file_offset;
  gboolean __isset_file_offset;
  gint64 total_compressed_size;
  gboolean __isset_total_compressed_size;
  gint16 ordinal;
  gboolean __isset_ordinal;
};
typedef struct _RowGroup RowGroup;

GType row_group_get_type (void);
gint32
row_group_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
gint32
row_group_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
void
row_group_finalize (GObject *object);
#define TYPE_ROW_GROUP (row_group_get_type())
#define ROW_GROUP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_ROW_GROUP, RowGroup))
void
row_group_instance_init (RowGroup * object);
#define IS_ROW_GROUP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_ROW_GROUP))

/* struct TypeDefinedOrder */
struct _TypeDefinedOrder
{
  ThriftStruct parent;

  /* public */
};
typedef struct _TypeDefinedOrder TypeDefinedOrder;

GType type_defined_order_get_type (void);
gint32
type_defined_order_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
gint32
type_defined_order_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
void
type_defined_order_finalize (GObject *object);
#define TYPE_TYPE_DEFINED_ORDER (type_defined_order_get_type())
#define TYPE_DEFINED_ORDER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TYPE_DEFINED_ORDER, TypeDefinedOrder))
void
type_defined_order_instance_init (TypeDefinedOrder * object);
#define IS_TYPE_DEFINED_ORDER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TYPE_DEFINED_ORDER))

/* struct ColumnOrder */
struct _ColumnOrder
{
  ThriftStruct parent;

  /* public */
  TypeDefinedOrder * TYPE_ORDER;
  gboolean __isset_TYPE_ORDER;
};
typedef struct _ColumnOrder ColumnOrder;

GType column_order_get_type (void);
gint32
column_order_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
gint32
column_order_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
void
column_order_finalize (GObject *object);
#define TYPE_COLUMN_ORDER (column_order_get_type())
#define COLUMN_ORDER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_COLUMN_ORDER, ColumnOrder))
void
column_order_instance_init (ColumnOrder * object);
#define IS_COLUMN_ORDER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_COLUMN_ORDER))

/* struct PageLocation */
struct _PageLocation
{
  ThriftStruct parent;

  /* public */
  gint64 offset;
  gint32 compressed_page_size;
  gint64 first_row_index;
};
typedef struct _PageLocation PageLocation;

GType page_location_get_type (void);
gint32
page_location_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
gint32
page_location_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
void
page_location_finalize (GObject *object);
#define TYPE_PAGE_LOCATION (page_location_get_type())
#define PAGE_LOCATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_PAGE_LOCATION, PageLocation))
void
page_location_instance_init (PageLocation * object);
#define IS_PAGE_LOCATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_PAGE_LOCATION))

/* struct OffsetIndex */
struct _OffsetIndex
{
  ThriftStruct parent;

  /* public */
  GPtrArray * page_locations;
  GArray * unencoded_byte_array_data_bytes;
  gboolean __isset_unencoded_byte_array_data_bytes;
};
typedef struct _OffsetIndex OffsetIndex;

GType offset_index_get_type (void);
gint32
offset_index_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
gint32
offset_index_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
void
offset_index_finalize (GObject *object);
#define TYPE_OFFSET_INDEX (offset_index_get_type())
#define OFFSET_INDEX(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_OFFSET_INDEX, OffsetIndex))
void
offset_index_instance_init (OffsetIndex * object);
#define IS_OFFSET_INDEX(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_OFFSET_INDEX))

/* struct ColumnIndex */
struct _ColumnIndex
{
  ThriftStruct parent;

  /* public */
  GArray * null_pages;
  GPtrArray * min_values;
  GPtrArray * max_values;
  BoundaryOrder boundary_order;
  GArray * null_counts;
  gboolean __isset_null_counts;
  GArray * repetition_level_histograms;
  gboolean __isset_repetition_level_histograms;
  GArray * definition_level_histograms;
  gboolean __isset_definition_level_histograms;
};
typedef struct _ColumnIndex ColumnIndex;

GType column_index_get_type (void);
gint32
column_index_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
gint32
column_index_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
void
column_index_finalize (GObject *object);
#define TYPE_COLUMN_INDEX (column_index_get_type())
#define COLUMN_INDEX(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_COLUMN_INDEX, ColumnIndex))
void
column_index_instance_init (ColumnIndex * object);
#define IS_COLUMN_INDEX(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_COLUMN_INDEX))

/* struct AesGcmV1 */
struct _AesGcmV1
{
  ThriftStruct parent;

  /* public */
  GByteArray * aad_prefix;
  gboolean __isset_aad_prefix;
  GByteArray * aad_file_unique;
  gboolean __isset_aad_file_unique;
  gboolean supply_aad_prefix;
  gboolean __isset_supply_aad_prefix;
};
typedef struct _AesGcmV1 AesGcmV1;

GType aes_gcm_v1_get_type (void);
gint32
aes_gcm_v1_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
gint32
aes_gcm_v1_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
void
aes_gcm_v1_finalize (GObject *object);
#define TYPE_AES_GCM_V1 (aes_gcm_v1_get_type())
#define AES_GCM_V1(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_AES_GCM_V1, AesGcmV1))
void
aes_gcm_v1_instance_init (AesGcmV1 * object);

#define AES_GCM_V1_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_AES_GCM_V1, AesGcmV1Class))
#define IS_AES_GCM_V1(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_AES_GCM_V1))

#define AES_GCM_V1_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_AES_GCM_V1, AesGcmV1Class))

/* struct AesGcmCtrV1 */
struct _AesGcmCtrV1
{
  ThriftStruct parent;

  /* public */
  GByteArray * aad_prefix;
  gboolean __isset_aad_prefix;
  GByteArray * aad_file_unique;
  gboolean __isset_aad_file_unique;
  gboolean supply_aad_prefix;
  gboolean __isset_supply_aad_prefix;
};
typedef struct _AesGcmCtrV1 AesGcmCtrV1;

GType aes_gcm_ctr_v1_get_type (void);
gint32
aes_gcm_ctr_v1_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
gint32
aes_gcm_ctr_v1_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
void
aes_gcm_ctr_v1_finalize (GObject *object);
#define TYPE_AES_GCM_CTR_V1 (aes_gcm_ctr_v1_get_type())
#define AES_GCM_CTR_V1(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_AES_GCM_CTR_V1, AesGcmCtrV1))
void
aes_gcm_ctr_v1_instance_init (AesGcmCtrV1 * object);

#define AES_GCM_CTR_V1_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_AES_GCM_CTR_V1, AesGcmCtrV1Class))
#define IS_AES_GCM_CTR_V1(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_AES_GCM_CTR_V1))

#define AES_GCM_CTR_V1_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_AES_GCM_CTR_V1, AesGcmCtrV1Class))

/* struct EncryptionAlgorithm */
struct _EncryptionAlgorithm
{
  ThriftStruct parent;

  /* public */
  AesGcmV1 * AES_GCM_V1;
  gboolean __isset_AES_GCM_V1;
  AesGcmCtrV1 * AES_GCM_CTR_V1;
  gboolean __isset_AES_GCM_CTR_V1;
};
typedef struct _EncryptionAlgorithm EncryptionAlgorithm;

GType encryption_algorithm_get_type (void);
gint32
encryption_algorithm_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
gint32
encryption_algorithm_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
void
encryption_algorithm_finalize (GObject *object);
#define TYPE_ENCRYPTION_ALGORITHM (encryption_algorithm_get_type())
#define ENCRYPTION_ALGORITHM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_ENCRYPTION_ALGORITHM, EncryptionAlgorithm))
void
encryption_algorithm_instance_init (EncryptionAlgorithm * object);
#define IS_ENCRYPTION_ALGORITHM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_ENCRYPTION_ALGORITHM))

/* struct FileMetaData */
struct _FileMetaData
{
  ThriftStruct parent;

  /* public */
  gint32 version;
  GPtrArray * schema;
  gint64 num_rows;
  GPtrArray * row_groups;
  GPtrArray * key_value_metadata;
  gboolean __isset_key_value_metadata;
  gchar * created_by;
  gboolean __isset_created_by;
  GPtrArray * column_orders;
  gboolean __isset_column_orders;
  EncryptionAlgorithm * encryption_algorithm;
  gboolean __isset_encryption_algorithm;
  GByteArray * footer_signing_key_metadata;
  gboolean __isset_footer_signing_key_metadata;
};
typedef struct _FileMetaData FileMetaData;

GType file_meta_data_get_type (void);
gint32
file_meta_data_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
gint32
file_meta_data_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
void
file_meta_data_finalize (GObject *object);
#define TYPE_FILE_META_DATA (file_meta_data_get_type())
#define FILE_META_DATA(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_FILE_META_DATA, FileMetaData))
void
file_meta_data_instance_init (FileMetaData * object);
#define IS_FILE_META_DATA(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_FILE_META_DATA))

/* struct FileCryptoMetaData */
struct _FileCryptoMetaData
{
  ThriftStruct parent;

  /* public */
  EncryptionAlgorithm * encryption_algorithm;
  GByteArray * key_metadata;
  gboolean __isset_key_metadata;
};
typedef struct _FileCryptoMetaData FileCryptoMetaData;

GType file_crypto_meta_data_get_type (void);
gint32
file_crypto_meta_data_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
gint32
file_crypto_meta_data_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error);
void
file_crypto_meta_data_finalize (GObject *object);
#define TYPE_FILE_CRYPTO_META_DATA (file_crypto_meta_data_get_type())
#define FILE_CRYPTO_META_DATA(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_FILE_CRYPTO_META_DATA, FileCryptoMetaData))
void
file_crypto_meta_data_instance_init (FileCryptoMetaData * object);
#define IS_FILE_CRYPTO_META_DATA(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_FILE_CRYPTO_META_DATA))

/*
 * -----------------------------------------------------------------------------
 * Special functions for FreeBIE repartitioning:
 * To import existing row groups to the new file metadata, we need the functions
 * for (1) extracting row group in byte stream and (2) injecting the byte stream
 * while writing the file metadata.
 * -----------------------------------------------------------------------------
 */
gint32 file_meta_data_read_extract_row_groups_binary (GByteArray **row_groups,
                                                      gint32 *num_row_groups,
                                                      gint64 *num_rows,
                                                      ThriftProtocol *protocol,
                                                      GError **error);

gint32 file_meta_data_write_inject_row_group_binary (ThriftStruct *object,
                                                     GByteArray *row_groups,
                                                     gint32 num_row_groups,
                                                     ThriftProtocol *protocol,
                                                     GError **error);

/* constants */

#endif /* PARQUET_TYPES_H */
